include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - directives_ordering
    - avoid_relative_lib_imports
    - prefer_relative_imports
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each