# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new internal build to Google Play"
  lane :internal do  
    sh "flutter build appbundle --dart-define-from-file=.env"
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
    )
  end

  desc "Submit a new beta build to Google Play"
  lane :beta do  
    sh "flutter build appbundle --dart-define-from-file=.env"
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do    
    sh "flutter build appbundle --dart-define-from-file=.env"
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
    )
  end
end
