on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor

      - run: flutter config --enable-web

      - run: flutter pub get

      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter build web --base-href=/${{ github.event.repository.name }}/ --dart-define-from-file=.env

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./build/web
