name: Deploy to web
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter doctor

      - run: flutter config --enable-web

      - run: flutter pub get

      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter build web --dart-define-from-file=.env
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.DEPLOY_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXAMPLE_477B8 }}
          channelId: live
          projectId: example-477b8